# Generated by Django 6.0.3 on 2026-04-06 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='anio',
            field=models.IntegerField(help_text='Año de lanzamiento (entre 1888 y el año siguiente)', validators=[django.core.validators.MinValueValidator(1888, message='El año no puede ser menor a 1888 (origen del cine)'), django.core.validators.MaxValueValidator(2027, message='No se puede superar el año 2027')]),
        ),
    ]
