# Generated by Django 6.0.3 on 2026-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_contenido_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL del tráiler o película (YouTube, Vimeo, etc.)', null=True),
        ),
    ]
