# Generated by Django 6.0.4 on 2026-04-07 23:29

import catalogos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_contenido_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='anio',
            field=models.IntegerField(help_text='Año de lanzamiento (entre 1888 y el año siguiente)', validators=[django.core.validators.MinValueValidator(1888, message='El año no puede ser menor a 1888 (origen del cine)'), catalogos.models.validate_max_year]),
        ),
    ]
